name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (remove sensitive information like API keys)
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you running?
      placeholder: "3.9.7"
    validations:
      required: true

  - type: input
    id: bazarr-version
    attributes:
      label: Bazarr Version
      description: What version of Bazarr are you using?
      placeholder: "1.2.3"
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your configuration file (remove sensitive information like URLs, API keys, passwords)
      render: ini
      placeholder: |
        [bazarr]
        url = https://example.com
        api_key = [REDACTED]

        [auth]
        username = [REDACTED]
        password = [REDACTED]

        # ... rest of config

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have removed sensitive information from logs and configuration
          required: true
        - label: I have provided sufficient information to reproduce the issue
          required: true
